"""empty message

Revision ID: 86423660961b
Revises: 2206207d3aca
Create Date: 2022-04-24 13:20:19.362474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86423660961b'
down_revision = '2206207d3aca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('image_uri', sa.String(length=400), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    # ### end Alembic commands ###
